import { useState } from 'react'
import { ArrowUpRight, ArrowRight, BarChart3, Globe, PanelsTopLeft, Search, Plus, Command, LayoutDashboard, Users, Settings, ChevronRight, Check, X } from 'lucide-react'

const money = (n: number) => n.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 })
const periods = {
  '6 meses': [34, 48, 42, 63, 58, 84],
  'Este ano': [26, 38, 32, 52, 43, 60, 55, 72, 67, 81, 74, 96],
  '30 dias': [38, 31, 52, 46, 67, 58, 82],
}
type Period = keyof typeof periods
const tabs = [{ id: 'dashboard', icon: BarChart3, label: 'Dashboard', brand: 'pulse', type: 'Inteligência de negócio' }, { id: 'site', icon: Globe, label: 'Website', brand: 'finova', type: 'Fintech · site funcional' }, { id: 'crm', icon: PanelsTopLeft, label: 'Sistema CRM', brand: 'nexo', type: 'Gestão comercial' }]

function DashboardDemo() {
  const [period, setPeriod] = useState<Period>('6 meses')
  const [point, setPoint] = useState<number | null>(null)
  const [metric, setMetric] = useState<'Receita' | 'Clientes'>('Receita')
  const values = periods[period]
  const total = values.reduce((a, b) => a + b, 0)
  const labels = period === '30 dias' ? ['01', '05', '10', '15', '20', '25', '30'] : ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
  return <div className="p-dashboard"><aside className="p-sidebar"><b><Command size={21} /> pulse<span>®</span></b><span className="p-side-label">WORKSPACE</span><div className="selected"><LayoutDashboard size={16} /> Visão geral</div><div><BarChart3 size={16} /> Relatórios</div><div><Users size={16} /> Clientes</div><div><Settings size={16} /> Configurações</div><div className="p-profile"><span>AC</span><p>Ana Costa<small>Administradora</small></p></div></aside><div className="p-dashboard-main"><header><div><small>Seu negócio, em perspectiva</small><h3>Visão geral <span>✦</span></h3></div><div className="p-periods">{(Object.keys(periods) as Period[]).map(p => <button key={p} onClick={() => { setPeriod(p); setPoint(null) }} aria-pressed={period === p}>{p}</button>)}</div></header><div className="p-metrics">{[{ label: 'Receita total', value: money(total * 1000), change: '+18,6%' }, { label: 'Novos clientes', value: String(Math.round(total * .52)), change: '+12,4%' }, { label: 'Ticket médio', value: money(1923), change: '+5,2%' }].map(m => <div key={m.label}><small>{m.label}<ArrowUpRight size={15} /></small><strong>{m.value}</strong><p><span>{m.change}</span> vs. período anterior</p></div>)}</div><div className="p-dash-grid"><div className="p-chart-card"><div className="p-chart-heading"><div><h4>Evolução do negócio</h4><p>{point === null ? 'Selecione uma coluna para explorar os dados.' : `${labels[point]} · ${metric === 'Receita' ? money(values[point] * 1000) : `${Math.round(values[point] * .52)} novos clientes`}`}</p></div><div className="p-metric-tabs">{(['Receita', 'Clientes'] as const).map(m => <button key={m} onClick={() => setMetric(m)} aria-pressed={metric === m}>{m}</button>)}</div></div><div className="p-bars">{values.map((v, i) => <button key={`${period}-${i}`} className={point === i ? 'active' : ''} onClick={() => setPoint(i)} aria-label={`${labels[i]}: ${metric === 'Receita' ? money(v * 1000) : `${Math.round(v * .52)} clientes`}`} aria-pressed={point === i}><span style={{ height: `${v}%` }}><i>{metric === 'Receita' ? `${v}k` : Math.round(v * .52)}</i></span><small>{labels[i]}</small></button>)}</div></div><div className="p-channel-card"><h4>De onde vêm os resultados</h4><p>Receita por canal</p><div className="p-donut"><div><strong>100%</strong><small>conectado</small></div></div>{[{ label: 'Orgânico', value: 48 }, { label: 'Indicações', value: 32 }, { label: 'Campanhas', value: 20 }].map((c, i) => <div className={`p-channel channel-${i}`} key={c.label}><i /><span>{c.label}</span><b>{c.value}%</b></div>)}</div></div><footer><span><i /> Dados demonstrativos atualizados</span><span>Design de informação pela Koder ↗</span></footer></div></div>
}

function WebsiteDemo() {
  return <div className="p-finova">
    <div className="p-finova-header">
      <div><span>PROJETO WEB DESENVOLVIDO PELA KODER</span><h3>Finova<span>®</span></h3><p>Uma experiência fintech com cartões 3D, dashboards e interações reais.</p></div>
      <a href="/finova/index.html" target="_blank" rel="noopener noreferrer">Abrir site completo <ArrowUpRight size={17} /></a>
    </div>
    <iframe title="Site Finova interativo" src="/finova/index.html" loading="lazy" />
    <div className="p-finova-footer"><span>Role e explore a página dentro da prévia.</span><span>Marca conceitual · site funcional</span></div>
  </div>
}
type Deal = { id: number; name: string; company: string; value: number; stage: number; color: string }
const initialDeals: Deal[] = [{ id: 1, name: 'Marina Alves', company: 'Studio Bloom', value: 12500, stage: 0, color: '#ffe2d2' }, { id: 2, name: 'Pedro Martins', company: 'Atlas Digital', value: 8400, stage: 0, color: '#e2e5fc' }, { id: 3, name: 'Luiza Ribeiro', company: 'Horizonte Co.', value: 24000, stage: 1, color: '#dceee4' }, { id: 4, name: 'Rafael Lima', company: 'Nova Ventures', value: 18000, stage: 2, color: '#e2e5fc' }, { id: 5, name: 'Camila Rocha', company: 'Forma Estúdio', value: 15600, stage: 2, color: '#ffe2d2' }]
const stages = ['Novos contatos', 'Em negociação', 'Fechados']
function CrmDemo() {
  const [deals, setDeals] = useState(initialDeals)
  const [query, setQuery] = useState('')
  const [adding, setAdding] = useState(false)
  const [name, setName] = useState('')
  const [value, setValue] = useState('')
  const filtered = deals.filter(d => `${d.name} ${d.company}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="p-crm"><header><b><Command size={23} /> nexo<span>CRM</span></b><span className="p-crm-workspace">Workspace comercial <ChevronRight size={14} /> Pipeline</span><span className="p-crm-avatar">AC</span></header><div className="p-crm-main"><div className="p-crm-heading"><div><small>RELACIONAMENTOS QUE GERAM RESULTADOS</small><h3>Seu próximo negócio.</h3></div><button className="p-new-deal" onClick={() => setAdding(v => !v)} aria-expanded={adding}>{adding ? <X size={16} /> : <Plus size={16} />}{adding ? 'Cancelar' : 'Novo contato'}</button></div><div className="p-crm-summary"><span><b>{deals.length}</b> oportunidades</span><span><b>{money(deals.reduce((sum, d) => sum + d.value, 0))}</b> no pipeline</span><label><Search size={15} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar contato ou empresa" aria-label="Buscar contato ou empresa" /></label></div>{adding && <form className="p-deal-form" onSubmit={e => { e.preventDefault(); if (!name.trim()) return; setDeals(v => [...v, { id: Date.now(), name: name.trim(), company: 'Novo projeto', value: Number(value), stage: 0, color: '#dceee4' }]); setName(''); setValue(''); setQuery(''); setAdding(false) }}><label>Nome do contato<input autoFocus value={name} onChange={e => setName(e.target.value)} required maxLength={50} /></label><label>Valor estimado (R$)<input type="number" min="0" max="99999999" value={value} onChange={e => setValue(e.target.value)} required /></label><button type="submit"><Check size={16} /> Adicionar à demonstração</button></form>}<div className="p-pipeline">{stages.map((stage, i) => { const list = filtered.filter(d => d.stage === i); return <div className={`p-stage stage-${i}`} key={stage}><div className="p-stage-heading"><span><i />{stage}<b>{list.length}</b></span><small>{money(list.reduce((sum, d) => sum + d.value, 0))}</small></div>{list.map(d => <article key={d.id}><div className="p-deal-person"><span style={{ background: d.color }}>{d.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</span><div><h4>{d.name}</h4><small>{d.company}</small></div></div><strong>{money(d.value)}</strong><div className="p-deal-bottom"><span>{i === 2 ? '✓ Negócio conquistado' : 'Projeto personalizado'}</span><button onClick={() => setDeals(v => v.map(item => item.id === d.id ? { ...item, stage: (item.stage + 1) % 3 } : item))} aria-label={`${i === 2 ? 'Reabrir' : 'Avançar'} contato ${d.name}`} title={i === 2 ? 'Reabrir contato' : 'Avançar para próxima etapa'}>{i === 2 ? '↺' : <ArrowRight size={15} />}</button></div></article>)}{!list.length && <div className="p-empty">{query ? 'Nenhum contato encontrado.' : 'Novas oportunidades começam aqui.'}</div>}</div> })}</div><footer><span><i /> Ambiente de demonstração · alterações locais</span><button onClick={() => { setDeals(initialDeals); setQuery(''); setAdding(false) }}>Restaurar exemplo ↺</button></footer></div></div>
}

export function ProjectShowcase() {
  const [active, setActive] = useState('dashboard')
  const project = tabs.find(t => t.id === active)!
  return <section id="projetos" className="k-section p-showcase"><div className="k-section-heading"><div><span className="k-eyebrow">03 / IDEIAS QUE GANHAM VIDA</span><h2>Não só imagine.<br /><span>Experimente o que criamos.</span></h2></div><p>Conheça um site funcional desenvolvido pela Koder e explore demonstrações interativas de dados e sistemas.</p></div><div className="p-tab-row" role="tablist" aria-label="Projetos Koder">{tabs.map(t => <button key={t.id} id={`tab-${t.id}`} role="tab" aria-selected={active === t.id} aria-controls={`panel-${t.id}`} tabIndex={active === t.id ? 0 : -1} onKeyDown={e => { if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { e.preventDefault(); const i = tabs.findIndex(item => item.id === active); const next = tabs[(i + (e.key === 'ArrowRight' ? 1 : 2)) % 3]; setActive(next.id); document.getElementById(`tab-${next.id}`)?.focus() } }} onClick={() => setActive(t.id)}><t.icon size={18} /><span>{t.label}<small>{t.type}</small></span><ArrowUpRight size={16} /></button>)}</div><div className="p-project-frame"><div className="p-frame-bar"><span className="p-frame-dots"><i /><i /><i /></span><span>{project.brand}.demo / {project.type.toLowerCase()}</span><small>{active === 'site' ? 'SITE FUNCIONAL' : 'CONCEITO KODER'}</small></div><div id={`panel-${active}`} role="tabpanel" aria-labelledby={`tab-${active}`} className="p-panel" key={active}>{active === 'dashboard' ? <DashboardDemo /> : active === 'site' ? <WebsiteDemo /> : <CrmDemo />}</div></div><div className="p-showcase-caption"><span><i /> Finova: marca conceitual e site funcional · demais projetos demonstrativos</span><a href="#contato">Vamos criar o seu? <ArrowUpRight size={16} /></a></div></section>
}
